version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fitness_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-UserService}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_ADMIN_USER:-postgres} -d ${POSTGRES_DB:-UserService}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: fitness_redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-""} --appendonly yes
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  app:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: fitness_app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${APP_HTTP_PORT:-8080}:8080"
      - "${APP_GRPC_PORT:-9090}:9090"
    environment:
      HTTP_ADDR: ":8080"
      GRPC_ADDR: ":9090"
      TRAIN_GRPC_ADDR: "${TRAIN_GRPC_ADDR:-host.docker.internal:50051}"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-fitness_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-user_password}
      POSTGRES_DB: ${POSTGRES_DB:-UserService}
      POSTGRES_SSLMODE: disable
      
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-""}
      REDIS_DB: ${REDIS_DB:-0}
      
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER:-postgres}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-postgres}
    networks:
      - app-network
    restart: unless-stopped


  pgadmin:
    image: dpage/pgadmin4
    container_name: fitness_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
    name: fitness_postgres_data
  redis-data:
    name: fitness_redis_data
  pgadmin-data:
    name: fitness_pgadmin_data

networks:
  app-network:
    name: fitness_network
    driver: bridge